### ISSUE TITLE
Nightly Todo

### ISSUE THREAD

**Issue by macel94** [macel94/cloudnativeblazorpong#14]
- [ ] Use sql server edge container locally
- [ ] Add animation to remove stuttering between different ball positions

- [ ] Test reconnection of a player
- [ ] Test 

- [ ] Evaluate a pause button
- [ ] Add loader
- [ ] Every message should be sent by server and only displayed by clients, no client side logic for messages needed

**Comment by macel94** [comment]
- [ ] use fluentd to aggregate logs?
Or whatever with opentelemetry is the standard https://andrewlock.net/writing-logs-to-elasticsearch-with-fluentd-using-serilog-in-asp-net-core/
